async function createStripePrice(productId, currency, amount) {
    const price = await stripe.prices.create({
      product: productId,
      currency: currency,
      unit_amount: amount,
    });
  
    return price.id; // Return the Price ID generated by Stripe
  }